### ISSUE TITLE
Transliteration of ш and щ symbols seems wrong

### ISSUE THREAD

**Issue by varpa89** [alexeynobody/translit-dart#8]
_complicatedSymbols has next values    
'щ': 'shhch',
'ш': 'shh',

Shouldn't it be just like this?
'щ': 'sh',
'ш': 'sh',

**Comment by darkstarx** [comment]
This variant
```
ш -> sh
щ -> shch
```
seems right

See here for instance
https://www.translitteration.com/transliteration/en/russian/bgn-pcgn/
https://transliteration.ru/gosdep/

**Comment by alexey-nobody** [comment]
Hi guys, thanks for that. I will update the library later.

**Comment by alexey-nobody** [comment]
I started making the correction and remembered why I did it this way. The problem is that with this transliteration, the reverse conversion gets lost because ‘sh’ -> ‘ш’ and not ‘сх’.

This is an issue for words like 'исход', for example.

@varpa89 @darkstarx Any ideas?

**Comment by darkstarx** [comment]
Well, I personally don't need symmetric conversion, it's more important to have an accurate result. But if someone needs such a functionality, the best approach is to give an option which conversion is needed. It can be achieved by having different converters, symmetric and assymetric, or having an optional named argument of enum type in conversion methods.

**Comment by alexey-nobody** [comment]
I agree, I thought of this solution myself.
